#include "runtime_live.h"

#include "compilerapi/compiler.h"
#include "compilerapi/compiler_source.h"
#include "cache/cache_constants.h"
#include "cache/cache_manager.h"
#include "cache/persistent_storage.h"
#include "flux/terminal/terminal_output_renderer.h"
#include "helper/string.h"
#include "compilerapi/runtime_live_summary.h"

#include <absl/strings/str_cat.h>
#include <absl/strings/str_join.h>

#include <filesystem>
#include <sstream>

namespace {

bool IsCppLanguage(const std::string& language) {
    return language == "cpp" || language == "cxx" || language == "c++";
}

bool SaveCompilableEntryCc(
    Engine::Cache::PersistentStorage* storage,
    const std::vector<std::string>& compile_units,
    std::string* write_error) {
    if (storage == nullptr || compile_units.empty()) {
        return true;
    }

    std::ostringstream entry_source;
    entry_source << "// Auto-generated compile entry (preserved)\n";
    entry_source << "// Generated by RuntimeLive::InterfaceCompiler\n\n";
    for (const std::string& unit : compile_units) {
        entry_source << "#include \"" << unit << "\"\n";
    }

    return storage->WriteTextRelative("entry.cc", entry_source.str(), write_error);
}

std::string BuildRuntimeLiveCacheKey(
    const std::string& provider,
    const std::string& language,
    const std::string& compile_flags,
    const std::string& link_flags,
    const std::string& source,
    const std::vector<RuntimeLive::InterfaceCompiler::SourceFile>& source_files) {
    std::vector<std::string> descriptors;
    descriptors.reserve(source_files.size());
    for (const auto& file : source_files) {
        descriptors.push_back(absl::StrCat(file.path, ":", file.content.size(), ":", file.is_header ? "h" : "s"));
    }
    return absl::StrCat(
        provider, "|",
        language, "|",
        compile_flags, "|",
        link_flags, "|",
        source.size(), "|",
        absl::StrJoin(descriptors, ","));
}

void EmitText(const RuntimeLive::RuntimeCallbacks* callbacks,
          flux::terminal::OutputStream stream,
          const std::string& text) {
    if (callbacks != nullptr) {
        if (stream == flux::terminal::OutputStream::kStdout && callbacks->raw_out) {
            callbacks->raw_out(text);
            return;
        }
        if (stream == flux::terminal::OutputStream::kStderr && callbacks->raw_err) {
            callbacks->raw_err(text);
            return;
        }
    }
    if (!text.empty()) {
        flux::terminal::Write(stream, text);
    }
}

std::string RelativeArtifactPath(const std::filesystem::path& root,
                 const std::filesystem::path& path) {
    const std::filesystem::path relative = path.lexically_relative(root);
    return relative.empty() ? path.filename().string() : relative.string();
}

std::string ReadArtifactText(const Engine::Cache::PersistentStorage& storage,
                 const std::filesystem::path& root,
                 const std::filesystem::path& path) {
    std::string text;
    std::string error;
    storage.ReadTextRelative(RelativeArtifactPath(root, path), &text, &error);
    return text;
}

}  // namespace

bool RuntimeLive::InterfaceCompiler::CompileAndRun(
    ExecutionResult* result,
    const RuntimeCallbacks* callbacks) const {
    ExecutionResult local_result;
    ExecutionResult* out = result != nullptr ? result : &local_result;
    *out = ExecutionResult();

	const std::filesystem::path effective_cache_dir = cache_dir_.empty()
		? Engine::Cache::CacheManager::Instance().DirectoryFor(
			Engine::Cache::constants::kRuntimeLiveScope,
			BuildRuntimeLiveCacheKey(provider_, language_, compile_flags_, link_flags_, source_, source_files_))
		: std::filesystem::path(cache_dir_);
	out->cache_dir = effective_cache_dir.string();
	Engine::Cache::PersistentStorage storage(effective_cache_dir);

    const auto emit_out = [&](const std::string& text) {
		EmitText(callbacks, flux::terminal::OutputStream::kStdout, text);
    };
    const auto emit_err = [&](const std::string& text) {
		EmitText(callbacks, flux::terminal::OutputStream::kStderr, text);
    };

    if (effective_cache_dir.empty() || (source_.empty() && source_files_.empty())) {
        out->error = "Cache directory or source is empty.";
        emit_err(out->error + "\n");
        return false;
    }

	std::string cache_error;
	if (!storage.EnsureRootDirectory(&cache_error)) {
		out->error = cache_error.empty() ? "Unable to create cache directory." : cache_error;
		emit_err(out->error + "\n");
		return false;
	}

    std::vector<std::string> compile_units;
    if (source_files_.empty()) {
        const CompilerSource compiler_source(
            source_,
            effective_cache_dir.string(),
            provider_,
            language_,
            compile_flags_,
            link_flags_);
        std::string write_error;
        if (!storage.WriteTextRelative(
			RelativeArtifactPath(effective_cache_dir, compiler_source.source_path()),
			compiler_source.source_with_stdio(),
			&write_error)) {
            out->error = "Unable to write source file.";
            emit_err(out->error + "\n");
            if (!write_error.empty()) {
                emit_err(write_error + "\n");
            }
            return false;
        }
    } else {
        for (const SourceFile& source_file_entry : source_files_) {
            std::string write_error;
            if (!storage.WriteTextRelative(
				source_file_entry.path,
                    source_file_entry.content,
                    &write_error)) {
                out->error = "Unable to write source file.";
                emit_err(out->error + "\n");
                if (!write_error.empty()) {
                    emit_err(write_error + "\n");
                }
                return false;
            }

            if (!source_file_entry.is_header) {
                compile_units.push_back(source_file_entry.path);
            }
        }

        if (compile_units.empty()) {
            out->error = "No source files provided for compilation.";
            emit_err(out->error + "\n");
            return false;
        }

        if (IsCppLanguage(language_)) {
            std::string write_error;
            if (!SaveCompilableEntryCc(&storage, compile_units, &write_error)) {
                out->error = "Unable to preserve entry.cc.";
                emit_err(out->error + "\n");
                if (!write_error.empty()) {
                    emit_err(write_error + "\n");
                }
                return false;
            }
        }
    }

    const CompilerSource compiler_source(
        source_,
        effective_cache_dir.string(),
        provider_,
        language_,
        compile_flags_,
        link_flags_,
        compile_units);

    const Compiler compiler;
    Compiler::ExecutionReport report;
    if (!compiler.CompileAndRunDetailed(compiler_source, &report)) {
        out->error = "Failed to invoke Clang/LLVM compilation API.";
        emit_err(out->error + "\n");
        return false;
    }

    out->summary.compile_exit_code = report.compile_exit_code;
    out->summary.run_exit_code = report.run_exit_code;
    out->summary.compile_invoked = report.compile_invoked;
    out->summary.run_invoked = report.run_invoked;
    out->summary.source_units = static_cast<int>(compile_units.empty() ? 1 : compile_units.size());
    out->summary.compiler_binary = report.compiler_binary;
    out->compiler_args = report.compiler_args;
    if (!report.compiler_binary.empty()) {
        out->summary.compiler_command = compiler_source.BuildCompilerCommandPreview(report.compiler_binary);
    }

    out->source_path = compiler_source.source_path().string();
    out->binary_path = compiler_source.binary_path().string();
    out->compile_out_path = compiler_source.compile_out_path().string();
    out->compile_err_path = compiler_source.compile_err_path().string();
    out->run_out_path = compiler_source.run_out_path().string();
    out->run_err_path = compiler_source.run_err_path().string();
    out->compile_stdout = ReadArtifactText(storage, effective_cache_dir, compiler_source.compile_out_path());
    out->compile_stderr = ReadArtifactText(storage, effective_cache_dir, compiler_source.compile_err_path());

    emit_out(out->compile_stdout);
    emit_err(out->compile_stderr);

    emit_out(BuildRuntimeLiveSummaryText(out->summary));

    if (report.compile_exit_code != 0) {
        out->ok = false;
        return false;
    }

    out->run_stdout = ReadArtifactText(storage, effective_cache_dir, compiler_source.run_out_path());
    out->run_stderr = ReadArtifactText(storage, effective_cache_dir, compiler_source.run_err_path());

    emit_out(out->run_stdout);
    emit_err(out->run_stderr);

    out->ok = report.run_exit_code == 0;
    return out->ok;
}

bool RuntimeLive::InterfaceCompiler::Runtime(const RuntimeCallbacks& callbacks) const {
    return CompileAndRun(nullptr, &callbacks);
}
