#include "runtime_live.h"

#include "compiler.h"
#include "compiler_source.h"
#include "runtime_live_summary.h"
#include "helper/tool_to.h"

#include <filesystem>
#include <sstream>

namespace {

bool IsCppLanguage(const std::string& language) {
    return language == "cpp" || language == "cxx" || language == "c++";
}

bool SaveCompilableEntryCc(
    const std::string& cache_dir,
    const std::vector<std::string>& compile_units,
    std::string* write_error) {
    if (compile_units.empty()) {
        return true;
    }

    std::ostringstream entry_source;
    entry_source << "// Auto-generated compile entry (preserved)\n";
    entry_source << "// Generated by RuntimeLive::InterfaceCompiler\n\n";
    for (const std::string& unit : compile_units) {
        entry_source << "#include \"" << unit << "\"\n";
    }

    return ToolTo::WriteTextFile(
        std::filesystem::path(cache_dir) / "entry.cc",
        entry_source.str(),
        false,
        write_error);
}

}  // namespace

bool RuntimeLive::InterfaceCompiler::CompileAndRun(
    ExecutionResult* result,
    const RuntimeCallbacks* callbacks) const {
    ExecutionResult local_result;
    ExecutionResult* out = result != nullptr ? result : &local_result;
    *out = ExecutionResult();
    out->cache_dir = cache_dir_;

    const auto emit_out = [&](const std::string& text) {
        if (callbacks != nullptr && callbacks->raw_out) {
            callbacks->raw_out(text);
        }
    };
    const auto emit_err = [&](const std::string& text) {
        if (callbacks != nullptr && callbacks->raw_err) {
            callbacks->raw_err(text);
        }
    };

    if (cache_dir_.empty() || (source_.empty() && source_files_.empty())) {
        out->error = "Cache directory or source is empty.";
        emit_err(out->error + "\n");
        return false;
    }

    std::error_code ec;
    std::filesystem::create_directories(cache_dir_, ec);
    if (ec) {
        out->error = "Unable to create cache directory.";
        emit_err(out->error + "\n");
        return false;
    }

    std::vector<std::string> compile_units;
    if (source_files_.empty()) {
        const CompilerSource compiler_source(
            source_,
            cache_dir_,
            provider_,
            language_,
            compile_flags_,
            link_flags_);
        std::string write_error;
        if (!ToolTo::WriteTextFile(
                compiler_source.source_path(),
                compiler_source.source_with_stdio(),
                false,
                &write_error)) {
            out->error = "Unable to write source file.";
            emit_err(out->error + "\n");
            if (!write_error.empty()) {
                emit_err(write_error + "\n");
            }
            return false;
        }
    } else {
        for (const SourceFile& source_file_entry : source_files_) {
            const std::filesystem::path file_path =
                std::filesystem::path(cache_dir_) / source_file_entry.path;
            std::error_code dir_ec;
            std::filesystem::create_directories(file_path.parent_path(), dir_ec);
            if (dir_ec) {
                out->error = "Unable to create source directory structure.";
                emit_err(out->error + "\n");
                return false;
            }

            std::string write_error;
            if (!ToolTo::WriteTextFile(
                    file_path,
                    source_file_entry.content,
                    false,
                    &write_error)) {
                out->error = "Unable to write source file.";
                emit_err(out->error + "\n");
                if (!write_error.empty()) {
                    emit_err(write_error + "\n");
                }
                return false;
            }

            if (!source_file_entry.is_header) {
                compile_units.push_back(source_file_entry.path);
            }
        }

        if (compile_units.empty()) {
            out->error = "No source files provided for compilation.";
            emit_err(out->error + "\n");
            return false;
        }

        if (IsCppLanguage(language_)) {
            std::string write_error;
            if (!SaveCompilableEntryCc(cache_dir_, compile_units, &write_error)) {
                out->error = "Unable to preserve entry.cc.";
                emit_err(out->error + "\n");
                if (!write_error.empty()) {
                    emit_err(write_error + "\n");
                }
                return false;
            }
        }
    }

    const CompilerSource compiler_source(
        source_,
        cache_dir_,
        provider_,
        language_,
        compile_flags_,
        link_flags_,
        compile_units);

    const Compiler compiler;
    Compiler::ExecutionReport report;
    if (!compiler.CompileAndRunDetailed(compiler_source, &report)) {
        out->error = "Failed to invoke Clang/LLVM compilation API.";
        emit_err(out->error + "\n");
        return false;
    }

    out->summary.compile_exit_code = report.compile_exit_code;
    out->summary.run_exit_code = report.run_exit_code;
    out->summary.compile_invoked = report.compile_invoked;
    out->summary.run_invoked = report.run_invoked;
    out->summary.source_units = static_cast<int>(compile_units.empty() ? 1 : compile_units.size());
    out->summary.compiler_binary = report.compiler_binary;
    out->compiler_args = report.compiler_args;
    if (!report.compiler_binary.empty()) {
        out->summary.compiler_command = compiler_source.BuildCompilerCommandPreview(report.compiler_binary);
    }

    out->source_path = compiler_source.source_path().string();
    out->binary_path = compiler_source.binary_path().string();
    out->compile_out_path = compiler_source.compile_out_path().string();
    out->compile_err_path = compiler_source.compile_err_path().string();
    out->run_out_path = compiler_source.run_out_path().string();
    out->run_err_path = compiler_source.run_err_path().string();
    out->compile_stdout = ToolTo::ReadTextFile(compiler_source.compile_out_path());
    out->compile_stderr = ToolTo::ReadTextFile(compiler_source.compile_err_path());

    emit_out(out->compile_stdout);
    emit_err(out->compile_stderr);

    emit_out(BuildRuntimeLiveSummaryText(out->summary));

    if (report.compile_exit_code != 0) {
        out->ok = false;
        return false;
    }

    out->run_stdout = ToolTo::ReadTextFile(compiler_source.run_out_path());
    out->run_stderr = ToolTo::ReadTextFile(compiler_source.run_err_path());

    emit_out(out->run_stdout);
    emit_err(out->run_stderr);

    out->ok = report.run_exit_code == 0;
    return out->ok;
}

bool RuntimeLive::InterfaceCompiler::Runtime(const RuntimeCallbacks& callbacks) const {
    return CompileAndRun(nullptr, &callbacks);
}
