#include "runtime_live.h"

#include "compiler.h"
#include "compiler_source.h"
#include "runtime_live_summary.h"
#include "helper/tool_to.h"

#include <filesystem>
#include <sstream>

namespace {

bool IsCppLanguage(const std::string& language) {
    return language == "cpp" || language == "cxx" || language == "c++";
}

bool SaveCompilableEntryCc(
    const std::string& cache_dir,
    const std::vector<std::string>& compile_units,
    std::string* write_error) {
    if (compile_units.empty()) {
        return true;
    }

    std::ostringstream entry_source;
    entry_source << "// Auto-generated compile entry (preserved)\n";
    entry_source << "// Generated by RuntimeLive::InterfaceCompiler\n\n";
    for (const std::string& unit : compile_units) {
        entry_source << "#include \"" << unit << "\"\n";
    }

    return ToolTo::WriteTextFile(
        std::filesystem::path(cache_dir) / "entry.cc",
        entry_source.str(),
        false,
        write_error);
}

}  // namespace

bool RuntimeLive::InterfaceCompiler::Runtime(const RuntimeCallbacks& callbacks) const {
    if (cache_dir_.empty() || (source_.empty() && source_files_.empty())) {
        if (callbacks.raw_err) {
            callbacks.raw_err("Cache directory or source is empty.\n");
        }
        return false;
    }

    std::error_code ec;
    std::filesystem::create_directories(cache_dir_, ec);
    if (ec) {
        if (callbacks.raw_err) {
            callbacks.raw_err("Unable to create cache directory.\n");
        }
        return false;
    }

    std::vector<std::string> compile_units;
    if (source_files_.empty()) {
        const CompilerSource compiler_source(
            source_,
            cache_dir_,
            provider_,
            language_,
            compile_flags_,
            link_flags_);
        std::string write_error;
        if (!ToolTo::WriteTextFile(
                compiler_source.source_path(),
                compiler_source.source_with_stdio(),
                false,
                &write_error)) {
            if (callbacks.raw_err) {
                callbacks.raw_err("Unable to write source file.\n");
                if (!write_error.empty()) {
                    callbacks.raw_err(write_error + "\n");
                }
            }
            return false;
        }
    } else {
        for (const SourceFile& source_file_entry : source_files_) {
            const std::filesystem::path file_path =
                std::filesystem::path(cache_dir_) / source_file_entry.path;
            std::error_code dir_ec;
            std::filesystem::create_directories(file_path.parent_path(), dir_ec);
            if (dir_ec) {
                if (callbacks.raw_err) {
                    callbacks.raw_err("Unable to create source directory structure.\n");
                }
                return false;
            }

            std::string write_error;
            if (!ToolTo::WriteTextFile(
                    file_path,
                    source_file_entry.content,
                    false,
                    &write_error)) {
                if (callbacks.raw_err) {
                    callbacks.raw_err("Unable to write source file.\n");
                    if (!write_error.empty()) {
                        callbacks.raw_err(write_error + "\n");
                    }
                }
                return false;
            }

            if (!source_file_entry.is_header) {
                compile_units.push_back(source_file_entry.path);
            }
        }

        if (compile_units.empty()) {
            if (callbacks.raw_err) {
                callbacks.raw_err("No source files provided for compilation.\n");
            }
            return false;
        }

        if (IsCppLanguage(language_)) {
            std::string write_error;
            if (!SaveCompilableEntryCc(cache_dir_, compile_units, &write_error)) {
                if (callbacks.raw_err) {
                    callbacks.raw_err("Unable to preserve entry.cc.\n");
                    if (!write_error.empty()) {
                        callbacks.raw_err(write_error + "\n");
                    }
                }
                return false;
            }
        }
    }

    const CompilerSource compiler_source(
        source_,
        cache_dir_,
        provider_,
        language_,
        compile_flags_,
        link_flags_,
        compile_units);

    const Compiler compiler;
    Compiler::ExecutionReport report;
    if (!compiler.CompileAndRunDetailed(compiler_source, &report)) {
        if (callbacks.raw_err) {
            callbacks.raw_err("Failed to invoke Clang/LLVM compilation API.\n");
        }
        return false;
    }

    RuntimeLiveSummary summary;
    summary.compile_exit_code = report.compile_exit_code;
    summary.run_exit_code = report.run_exit_code;
    summary.compile_invoked = report.compile_invoked;
    summary.run_invoked = report.run_invoked;
    summary.source_units = static_cast<int>(compile_units.empty() ? 1 : compile_units.size());
    summary.compiler_binary = report.compiler_binary;
    if (!report.compiler_binary.empty()) {
        summary.compiler_command = compiler_source.BuildCompilerCommandPreview(report.compiler_binary);
    }

    if (callbacks.raw_out) {
        callbacks.raw_out(ToolTo::ReadTextFile(compiler_source.compile_out_path()));
    }
    if (callbacks.raw_err) {
        callbacks.raw_err(ToolTo::ReadTextFile(compiler_source.compile_err_path()));
    }

    if (callbacks.raw_out) {
        callbacks.raw_out(BuildRuntimeLiveSummaryText(summary));
    }

    if (report.compile_exit_code != 0) {
        return false;
    }

    if (callbacks.raw_out) {
        callbacks.raw_out(ToolTo::ReadTextFile(compiler_source.run_out_path()));
    }
    if (callbacks.raw_err) {
        callbacks.raw_err(ToolTo::ReadTextFile(compiler_source.run_err_path()));
    }

    return report.run_exit_code == 0;
}
